config/routes.rb
Rails.application.routes.draw do

  resources :user_invitations, controller: :invitations,
    only: %i(index new create destroy ) do

    member do
      patch :resend
    end
  end

  if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # re-route some devise endpoints that are unused
  get '/users/edit',    to: redirect('/')
  get '/users/sign_up', to: redirect('/')
  match '/users', to: redirect('/'), via: %i(put patch post delete)

  mount Decidim::Core::Engine => '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area_of_interest.rb
# frozen_string_literal: true

class AreaOfInterest

  # Do not change the keys of this hash, they are referenced by
  # user.profile.areas_of_interest.
  ALL = {
    'human_rights' => 'Human rights & anti-discrimination (gender, race, minorities, disabilty etc.)',
    'climate_justice' => 'Climate justice & environment',
    'alt_economies' => 'Alternative economies (commons, circular economy, transition town etc.)',
    'alt_media' => 'Alternative media, arts & culture',
    'digital_activism' => 'Digital activism',
    'democratic_innovation' => 'Democratic innovation & civic education',
    'migration' => 'Migration',
    'civil_rights' => 'Civil, political & social rights',
  }.freeze

  def self.to_a
    ALL.to_a
  end

  def self.for(name)
    ALL[name]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :fund_action_authenticate_user!, if: :login_required?

  rescue_from StandardError, with: :report_error

  private

  def report_error(e)
    Rails.logger.error "\n\n\n#{e}\n\n"
    if defined? Airbrake
      Airbrake.notify e
    end
    raise e
  end

  # the aliasing prevents i.e. proposals_controller to change the condition
  alias fund_action_authenticate_user! authenticate_user!

  def login_required?
    unless %w(
      decidim/cookie_policy
      decidim/errors
      decidim/pages
      decidim/homepage
    ).include? params[:controller]

      return true
    end
  end
end

app/controllers/decidim_controller.rb
# Entry point for Decidim. It will use the `DecidimController` as
# entry point, but you can change what controller it inherits from
# so you can customize some methods.
class DecidimController < ApplicationController
end

app/controllers/invitations_controller.rb
# frozen_string_literal: true

class InvitationsController < Decidim::ApplicationController
  include Decidim::UserProfile

  helper 'decidim/admin/icon_link'

  before_action :check_remaining_invites, only: %i(new create)
  before_action :check_invitation_update, only: %i(resend destroy)


  def index
    @users = current_organization.users.
      where(invited_by: current_user).page(params[:page]).per(20).
      order(created_at: :asc)
  end

  def new
    @form = form(FundAction::InviteUserForm).instance
    @form.num_invites = 0 # default to 0 invites
  end

  def create
    @form = form(FundAction::InviteUserForm).from_params params

    FundAction::InviteUsers.(@form, current_user) do
      on(:ok) do |successes|
        flash[:notice] = I18n.t("invitations.sent", count: successes.size)
        redirect_to user_invitations_path
      end

      on(:invalid) do |successes, errors|
        if successes.any?
          flash.now[:alert] = I18n.t("invitations.some_errors", errors: errors.size, count: successes.size)
        else
          flash.now[:alert] = I18n.t("invitations.error", count: errors.size)
        end
        render :new
      end
    end

  end


  # resend invitation
  def resend
    Decidim::InviteUserAgain.(@invited_user, "invited_by_user") do
      on(:ok) do
        flash[:notice] = I18n.t("users.resend_invitation.success", scope: "decidim.admin")
      end

      on(:invalid) do
        flash[:alert] = I18n.t("users.resend_invitation.error", scope: "decidim.admin")
      end
    end

    redirect_to user_invitations_path
  end


  # revoke invitation
  def destroy
    FundAction::RemoveInvitation.(@invited_user) do
      on(:ok) do
        flash[:notice] = I18n.t("destroy.success", scope: "invitations")
      end

      on(:invalid) do
        flash[:alert] = I18n.t("destroy.error", scope: "invitations")
      end
    end

    redirect_to user_invitations_path
  end


  private

  def check_remaining_invites
    unless current_user.has_invitations_left?
      redirect_to user_invitations_path
      return false
    end
  end

  def check_invitation_update
    @invited_user = current_organization.users.find params[:id]

    if @invited_user&.invited_to_sign_up? and
      @invited_user.invited_by == current_user and
      !@invited_user.invitation_accepted?

      true
    else
      redirect_to user_invitations_path
      false
    end
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper

  def language_select_options(selected_languages = [])
    options_from_collection_for_select(
      LanguageList::COMMON_LANGUAGES.sort{|a,b|a.name <=> b.name},
      :iso_639_1, :name,
      selected_languages
    )
  end

  def area_of_interest_select_options(selected_areas_of_interest = [])
    options_from_collection_for_select(
      AreaOfInterest.to_a, :first, :last, selected_areas_of_interest
    )
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/decidim/account/_account_form_additional_attributes.html.erb
<% if form.object.values_accepted? %>
  <%= form.hidden_field :value_statement %>
<% else %>
  <p>
  Please take a few minutes to read the <a href="/fundaction_values.pdf">FundAction value statement</a>.<br />
    <%= form.check_box :value_statement, label: 'I read and accept the FundAction value statement' %>
  </p>
<% end %>

<%= form.check_box :public_email, label: 'Show my email address on my profile page so other members can contact me' %>

<%= form.text_field :gender %>
<p class="help-text"><%= t(".gender_hint") %></p>


<label for="user_country">
  <%= t 'country', scope: %i(activemodel attributes user) %>
  <%= form.country_select :country, { include_blank: true }, { data: { placeholder: t('.choose_country') } } %>
</label>

<%= form.select :languages, language_select_options(form.object.languages), {}, { multiple: true, data: { placeholder: t('.choose_languages') } } %>
<%= form.select :areas_of_interest, area_of_interest_select_options(form.object.areas_of_interest), {}, { multiple: true, data: { placeholder: t('.choose_areas_of_interest') } } %>
<%= form.text_field :other_area_of_interest, placeholder: t('.other_area_of_interest') %>

<%= form.editor :about_me, toolbar: :full, lines: 10 %>

<%= form.text_area :can_contribute, rows: 5 %>
<p class="help-text"><%= t(".can_contribute_hint") %></p>

<%= form.text_area :cultural_background, rows: 5 %>
<p class="help-text"><%= t(".cultural_background_hint") %></p>

app/views/decidim/account/show.html.erb
<div class="row">
  <%= decidim_form_for(@account, url: account_path, method: :put, class: "user-form", autocomplete: "nope") do |f| %>
    <div class="columns large-4">
      <%= f.upload :avatar %>
    </div>

    <div class="columns large-8 end">
      <%= f.text_field :name %>
      <%= f.text_field :nickname %>
      <%= f.email_field :email %>
      <%#= f.url_field :personal_url %>
      <%#= f.text_area :about, rows: 5 %>
      <%= render partial: 'account_form_additional_attributes', locals: { form: f } %>

      <% if @account.errors[:password].any? || @account.errors[:password_confirmation].any? %>
        <%= render partial: "password_fields", locals: { form: f } %>
      <% else %>
        <p>
          <a data-toggle="passwordChange" class="change-password"><%= t ".change_password" %></a>
        </p>
        <div id="passwordChange" class="toggle-show" data-toggler=".is-expanded">
          <%= render partial: "password_fields", locals: { form: f } %>
        </div>
      <% end %>

      <%= f.submit t(".update_account"), disable_with: true %>
    <% end %>
  </div>
</div>

app/views/decidim/members/_user_profile_bottom.html.erb
<% if country = user.country %>
  <p><%= t '.country', country: country %></p>
<% end %>

<% if languages = user.languages.presence %>
  <p><%= t '.i_speak', languages: languages.to_sentence %></p>
<% end %>

<% if areas_of_interest = user.areas_of_interest.presence %>
  <p><%= t '.areas_of_interest', areas: areas_of_interest.to_sentence %></p>
<% end %>

<% if user.about_me.present? %>
  <%= sanitize user.about_me %>
<% end %>

<% if user.public_email? %>
  <p><%= t '.you_can_reach_me_html', mail: mail_to(user.email) %></p>
<% end %>

<% if current_user&.admin? %>
  <h4>Private information</h4>
  <% unless user.public_email? %>
    <p>Email: <%= user.email %>
  <% end %>
  <p>
  <strong>Gender:</strong>
  <%= user.gender %>
  </p>
  <p>
    <strong>Can contribute</strong><br>
    <%= user.can_contribute %>
  </p>
  <p>
    <strong>Cultural background</strong><br>
    <%= user.cultural_background %>
  </p>
<% end %>

app/views/decidim/user_profiles/_user_profile_bottom.html.erb
<% if country = @user.country %>
  <p><%= t '.country', country: country %></p>
<% end %>

<% if languages = @user.languages.presence %>
  <p><%= t '.i_speak', languages: languages.to_sentence %></p>
<% end %>

<% if areas_of_interest = @user.areas_of_interest.presence %>
  <p><%= t '.areas_of_interest', areas: areas_of_interest.to_sentence %></p>
<% end %>

<% if @user.about_me.present? %>
  <%= sanitize @user.about_me %>
<% end %>


<% if current_user&.admin? %>
  <h4>Private information</h4>
  <p>
  <strong>Gender:</strong>
  <%= @user.gender %>
  </p>
  <p>
    <strong>Can contribute</strong><br>
    <%= @user.can_contribute %>
  </p>
<% end %>

app/views/fund_action/hooks/_user_profile_bottom.html.erb
<div class="card__content">
  <% if country = user.country %>
    <p><%= t '.country', country: country %></p>
  <% end %>

  <% if languages = user.languages.presence %>
    <p><%= t '.i_speak', languages: languages.to_sentence %></p>
  <% end %>

  <% if areas_of_interest = user.areas_of_interest.presence %>
    <p><%= t '.areas_of_interest', areas: areas_of_interest.to_sentence %></p>
  <% end %>

  <% if user.about_me.present? %>
    <%= sanitize user.about_me %>
  <% end %>

  <% if user.public_email? %>
    <p><%= t '.you_can_reach_me_html', mail: mail_to(user.email) %></p>
  <% end %>

  <% if current_user&.admin? %>
    <h1 class="profile--sidebar--title">
      <div><strong>Private information</strong></div>
    </h1>
    <% unless user.public_email? %>
      <p>Email: <%= user.email %>
    <% end %>
    <p>
    <strong>Gender:</strong>
    <%= user.gender %>
    </p>
    <p>
      <strong>Can contribute</strong><br>
      <%= user.can_contribute %>
    </p>
    <p>
      <strong>Cultural background</strong><br>
      <%= user.cultural_background %>
    </p>
  <% end %>

</div>

app/views/invitations/index.html.erb
<% if current_user.has_invitations_left? %>
  <%= link_to t('.new'), new_user_invitation_path, class: 'button' %>
<% else %>
  <p><%= t '.no_invitations' %></p>
<% end %>

<% if @users.any? %>
<div class="table-scroll">
  <table class="table-list">
    <thead>
      <tr>
        <th><%= t("models.user.fields.name", scope: "decidim.admin") %></th>
        <th><%= t("models.user.fields.email", scope: "decidim.admin") %></th>
        <th><%= t("models.user.fields.invitation_sent_at", scope: "decidim.admin") %></th>
        <th><%= t("models.user.fields.invitation_accepted_at", scope: "decidim.admin") %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr data-user-id="<%= user.id %>">
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <% if user.invitation_sent_at %>
              <%= l user.invitation_sent_at, format: :short %>
            <% end %>
          </td>
          <td>
            <% if user.invitation_accepted_at %>
              <%= l user.invitation_accepted_at, format: :short %>
            <% end %>
          </td>
          <td class="table-list__actions">
            <% if user.invited_to_sign_up? && !user.invitation_accepted? %>
              <%= icon_link_to "reload", resend_user_invitation_path(user), t("actions.resend_invitation", scope: "decidim.admin"), class: "resend-invitation", method: :patch %>

              <%= icon_link_to "circle-x", user_invitation_path(user), t("actions.destroy", scope: "decidim.admin"), class: "action-icon--remove", method: :delete, data: { confirm: t(".confirm_destroy") } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @users, theme: "decidim" %>
</div>
<% end %>

app/views/invitations/new.html.erb
<p>
  <% if current_user.invitation_limit %>
    <%= t '.you_have_x_invites_left', count: current_user.invitation_limit.to_i %>
  <% end %>

  <% if current_user.admin? %>
    <%= t '.admin_instructions' %>
    <small><pre>Jane Doe, jane.doe@example.org</pre></small>
  <% end %>
</p>

<%= decidim_form_for(@form, url: user_invitations_path, html: { class: "form new_user" }) do |f| %>
<div class="row column">
  <% if current_user.admin? %>
    <%= f.text_area :emails, label: t('.emails'), rows: 10 %>
    <%= f.text_field :num_invites, label: t('.num_invites') %>
  <% else %>
    <%= f.text_field :name, label: t('.name') %>
    <%= f.email_field :email, label: t('.email') %>
  <% end %>
</div>

<div class="button--double form-general-submit">
  <%= f.submit t(".create") %>
</div>
<% end %>

app/views/layouts/decidim/_user_menu.html.erb
<li><%= link_to t(".profile"), decidim.account_path %></li>
<% if current_user.nickname.present? && !current_user.managed? %>
  <li><%= link_to t(".public_profile"), decidim.profile_path(current_user.nickname) %></li>
<% end %>
<li><%= link_to t(".notifications"), decidim.notifications_path %></li>
<li><%= link_to t(".conversations"), decidim.conversations_path %></li>
<li><%= link_to t(".invite_friends"), main_app.user_invitations_path %></li>
<% if allowed_to? :read, :admin_dashboard %>
  <li><%= link_to t(".admin_dashboard"), decidim_admin.root_path %></li>
<% end %>
<li><%= link_to t(".sign_out"), decidim.destroy_user_session_path, method: :delete, class: "sign-out-link" %></li>

app/views/layouts/users.html.erb
<%= render "layouts/decidim/application" do %>
  <%= yield %>
<% end %>

app/views/pages/home/_extended.html.erb
<section class="extended">
  <div class="wrapper-home home-section">
    <div class="row column text-center">
      <h3 class="heading2"><%= t(".fundaction_grants") %></h3>
    </div>

    <div class="row small-up-1 medium-up-3 home-bullets">
      <div class="column">
        <div class="home-bullet">
          <div class="home-bullet__icon">
            <%= image_tag "rethink.png" %>
          </div>
          <!--
          <div class="home-bullet__desc">
            <h4 class="heading6"><%= t(".meetings") %></h4>
            <p><%= t(".meetings_explanation") %></p>
          </div>
          -->
        </div>
      </div>
      <div class="column">
        <div class="home-bullet">
          <div class="home-bullet__icon">
            <%= image_tag "renew.png" %>
          </div>
          <!--
          <div class="home-bullet__desc">
            <h4 class="heading6"><%= t(".debates") %></h4>
            <p><%= t(".debates_explanation") %></p>
          </div>
          -->
        </div>
      </div>
      <div class="column">
        <div class="home-bullet">
          <div class="home-bullet__icon">
            <%= image_tag "resist.png" %>
          </div>
          <!--
          <div class="home-bullet__desc">
            <h4 class="heading6"><%= t(".proposals") %></h4>
            <p><%= t(".proposals_explanation") %></p>
          </div>
          -->
        </div>
      </div>
    </div>
    <div class="row">
      <div class="columns small-centered small-10
                smallmedium-8 medium-6 large-4">
        <%= link_to t(".more_info"), decidim.page_path("grants"), class: "button expanded hollow button--sc" %>
      </div>
    </div>
  </div>
</section>

app/views/pages/home/_footer_sub_hero.html.erb
<section class="footer__subhero extended subhero home-section">
  <div class="row">
    <div class="columns small-centered large-10">
      <h2 class="heading3"><%= t(".fa_footer_sub_hero_headline", organization: current_organization.name) %></h2>
      <h5 class="heading4"><%== t(".fa_footer_sub_hero_body") %></h5>
      <a class="button--sc link subhero-cta" href="http://www.fundaction.eu">www.fundaction.eu</a>
    </div>
  </div>
</section>

app/views/pages/home/_sub_hero.html.erb
  <section class="extended subhero home-section">
    <div class="row">
      <div class="columns small-centered large-10">
        <h2 class="heading3"><%= sanitize translated_attribute current_organization.description %></h2>
        <a class="button--sc link subhero-cta" href="http://www.fundaction.eu">www.fundaction.eu</a>
      </div>
    </div>
  </section>